/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicSyncCatalogRouteImport } from './routes/api/public/sync-catalog'
import { Route as ApiPublicSeedCatalogRouteImport } from './routes/api/public/seed-catalog'

const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSyncCatalogRoute = ApiPublicSyncCatalogRouteImport.update({
  id: '/api/public/sync-catalog',
  path: '/api/public/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedCatalogRoute = ApiPublicSeedCatalogRouteImport.update({
  id: '/api/public/seed-catalog',
  path: '/api/public/seed-catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/api/public/seed-catalog': typeof ApiPublicSeedCatalogRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog': typeof CatalogIndexRoute
  '/api/public/seed-catalog': typeof ApiPublicSeedCatalogRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/api/public/seed-catalog': typeof ApiPublicSeedCatalogRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/contacts'
    | '/admin'
    | '/catalog/$slug'
    | '/product/$slug'
    | '/catalog/'
    | '/api/public/seed-catalog'
    | '/api/public/sync-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/contacts'
    | '/admin'
    | '/catalog/$slug'
    | '/product/$slug'
    | '/catalog'
    | '/api/public/seed-catalog'
    | '/api/public/sync-catalog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/contacts'
    | '/_authenticated/admin'
    | '/catalog/$slug'
    | '/product/$slug'
    | '/catalog/'
    | '/api/public/seed-catalog'
    | '/api/public/sync-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactsRoute: typeof ContactsRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ApiPublicSeedCatalogRoute: typeof ApiPublicSeedCatalogRoute
  ApiPublicSyncCatalogRoute: typeof ApiPublicSyncCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-catalog': {
      id: '/api/public/sync-catalog'
      path: '/api/public/sync-catalog'
      fullPath: '/api/public/sync-catalog'
      preLoaderRoute: typeof ApiPublicSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-catalog': {
      id: '/api/public/seed-catalog'
      path: '/api/public/seed-catalog'
      fullPath: '/api/public/seed-catalog'
      preLoaderRoute: typeof ApiPublicSeedCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactsRoute: ContactsRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ApiPublicSeedCatalogRoute: ApiPublicSeedCatalogRoute,
  ApiPublicSyncCatalogRoute: ApiPublicSyncCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
